# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.S')
libs    = ['airkiss']
libpath = [cwd]
CPPPATH = [os.path.join(cwd,'..')]
group = DefineGroup('airkiss', src, depend = [''], CPPPATH = CPPPATH,LIBS = libs, LIBPATH = libpath)

Return('group')
