# RT-Thread building script for component

from building import *
src = Glob('*.c')
cwd = GetCurrentDir()
CPPPATH = [cwd,os.path.join(cwd,'..','..')]

group = DefineGroup('samples', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
